.travis.yml
make/tester.rules

Travis CI configuration

---

src/mad_aper.c
src/mad_sdds.c
src/mad_table.c
src/mad_table.h
src/mad_track.c
src/mad_twiss.c

(just because I didn't like to look at hundreds of unreadable lines repeating the same thing)

Minor cleanup of table_add_header pattern

---

src/mad_gvar.c
src/mad_gvar.h
src/mad_inter.c
src/mad_twiss.c

Cleanup `interpolate_node`

---

src/mad_select.c

Make it easier to handle selects consistently.

Deduplicate some code for store_select/store_deselect

---

src/twiss.f90

Coupling included in the initialization of the sigma matrices. The flip mode is still to be tested.

Initialization of the sigma matrices.

---

src/mad_elem.c
src/mad_gvar.c
src/mad_gvar.h
src/mad_mkthin.cpp
src/mad_sdds.c
src/mad_select.c
src/mad_select.h
src/mad_seq.c
src/mad_table.c

Minor speed advantage on selection. Needed for properly removing shared drifts.

Few improvements for pass_select

---

src/mad_aper.c
src/mad_aper.h
src/mad_table.c

For review, more testing needed, address #384

add offset attributes to twiss table

---

src/mad_6track.c

Address #467. Not merge yet untill further decisions.

change sign of sixtrack separation

---

src/trrun.f90

* changed subroutine's title ("cosmetic" change)
* changed declaration of double precision complex to conform to other parts of the code

implemented comments on my previous pull request (unified thick tracking for combined function dipole)

---

src/trrun.f90

Implemented a couple of IFs to avoid useless computations.

Avoid useless computations, if bending or focusing strengths are zero

---

doc/latexuguide/changelog.tex

Document the removal drift sharing

---

doc/latexuguide/conventions.tex
doc/latexuguide/uguide.tex

I also updated the version number to the latest. Fixes: #470

Fixed error in defintion of the the T-variable for twiss. 

---

src/mad_dynap.c
src/mad_elemerr.c
src/mad_exec.c
src/mad_node.c
src/mad_orbit.c
src/mad_plot.c
src/mad_ptc.c
src/mad_sdds.c
src/mad_spch.c
src/mad_table.c
src/mad_table.h
src/mad_track.c
src/mad_twiss.c

Minor simplification to avoid the recurring `name_list_pos` pattern for this case.

Add find_table function

---

doc/latexuguide/thintrack.tex

This request documents the TRACK_HARMON option in track that is used to calculate t_max.

Added TRACK_HARMON to the documentation.

---

tests/test-elseparator/ELSEPARATOR.obs0001.p0001.cfg
tests/test-elseparator/ELSEPARATOR.obs0002.p0001.cfg

It gives slightly different results for the 32 bits so have to update the .cfg files.

Fixed the test for the elseparator

---

doc/latexuguide/elements.tex

This pull request fix this issue:
#513
I am not sure how I managed to push this to the main repository instead of my own.. anyway it is a small change so as soon it is merged we can delete it..

Fixed an error in the doc for how to kill edge effects.

---

Makefile_test
src/survey.f90
src/twiss.f90
tests/test-translation/offset.twiss.cfg
tests/test-translation/offset.twiss.ref
tests/test-translation/survey.out.cfg
tests/test-translation/survey.out.ref
tests/test-translation/test-translation.cfg
tests/test-translation/test-translation.madx
tests/test-translation/test-translation.ref
tests/test-translation/translation.twiss.cfg
tests/test-translation/translation.twiss.ref

This PR  implements the translation element in twiss. It also includes tests of the translation.

Add translation with tests

---

doc/latexuguide/ptc-auxiliaries.tex

The main change is a short text for the documentation of 'printparametric'. The rest is auto-formatting...

Adding documentation for ptc_printparametric.

---

libs/ptc/src/Sh_def_kind.f90
libs/ptc/src/Sma_multiparticle.f90
libs/ptc/src/Sra_fitting.f90
src/madx_ptc_module.f90
src/wrap.f90

- Bug correction: name of an internal PTC variable changed and was not correctly initialized in MADX
- Re-enabled aperture check at every step
- getmagnetic as a POTENTIAL replacement of getelectric for ptc's teapot
- Update of PTC

Bug correction and update of PTC (closed orbit search on 6D totpath)

---

src/plot.f90

This removes the check if the points are too close and plots all of them instead. This fixes the issue #575

Fix apperture plotting

---

src/mad_elem.c
src/mad_elemerr.c
src/mad_survey.c
src/survey.f90

…ld errors in efcomp by angle/l when k0 is 0 for consistency (after discussion with Riccardo)

update normalisation of field errors for k0=0

---

src/trrun.f90

Implemented field errors in thick quadrupole and thick dipole in TRACK.
It included Laurent's modification to implement K0 in sector bends.
For thick-dipole, the error is applied directly to K0. The equations show that this is equivalent to what TWISS does in tmbend, where the error is applied as 'dh'.

Added field errors to thick quadrupole and thick dipole in TRACK

---

Makefile_test
src/mad_node.c
tests/test-sequence-7/test-sequence-7.cfg
tests/test-sequence-7/test-sequence-7.madx
tests/test-sequence-7/test-sequence-7.ref
tests/test-sequence-7/twiss.out.cfg
tests/test-sequence-7/twiss.out.ref

This fixes the problem reported in #598. A test of this functionality was also added.

Fix the replace command that had unwanted side effects 

---

src/mad_exec.c
src/mad_seq.c
src/mad_seq.h

Hi,
I checked #602 in case it had something to do with the changes I made. Turns out it was preexisting, and there were a couple more lingering unreported related bugs.
Best, Thomas

Fix delete sequence

---

doc/latexuguide/ptc-general.tex

Some line end changes, but see mostly lines 298-302 of 'ptc-general.tex'.

Documentation of the PTC 'FRINGE' flag

---

make/compiler.lf95
src/mad_dbg.c
src/mad_dbg.h
src/mad_mac.h
src/mad_mkthin.cpp
src/madx.h

this option is automatically activated with DEBUG=yes

add new assertion that loops for dbg backtrace

---

src/mad_twiss.c

The problem comes after running several twiss. It fixes this issue #675

Fixes the memory corruption 

---

src/mad_seq.c

The main problem before was that the move command tried to move the element several times. This is fixed in this new PR.

Fixes the move command 

---

.travis.yml

- enable test-plot to run on travis
- cleanup some obsolete parts and comments in the travis config
- update for removal of container-based on travis

Enable test-plot on travis, some cleanup

---

src/emit.f90

This caused test-emit and test-emit-2 to fail on Ubuntu

Fixed problem with uninitialised variable

---

src/trrun.f90
tests/test-thick-rbend/track.obs0001.p0001.ref
tests/test-thick-rbend/track.obs0001.p0002.ref
tests/test-thick-rbend/track.obs0001.p0003.ref
tests/test-track-13/test-track-13.ref

In reference to Issue https://github.com/MethodicalAcceleratorDesign/MAD-X/issues/844

Fixed two typos in call to ttdpdg_map

---

doc/latexuguide/elements.tex
src/mad_mkthin.cpp
src/mad_seq.c
src/trrun.f90

Stops makethin if center is not chosen and adds drift to corrector if l>0.

---

src/mad_mkthin.cpp

This should fix the issue #881

Fixes the problem with derived elements 

---

doc/latexuguide/error.tex
src/mad_ptc.c

This PR fixes the issue with the warning when gcs was chosen #909

Fixing the gcs warning

---

doc/latexuguide/thintrack.tex

Documentation update for KEEPTRACK

Documentation update for issue 932

---

Makefile_f90
libs/ptc/Makefile_f90

Had a build failure since St_pointers contains a use statement for duan_zhe_map. This fixed it.

Added a dependency for St_pointers on Su_duan_zhe_map

---

Makefile_lnx
make/make.cfg
src/mad_elem.c

fixes to overcome bug and back incompatibility from make 4.3

make 4.3 fixes

---

src/mad_6track.c

This should fix the issue in #964

Fix so crab voltage is not included to the total voltage.

---

src/mad_elem.c
tests/test-sequence-2/test-sequence-2.ref

If the name is too long then an error will be thrown..

This is a fix for the too long name of the sequence. 

---

.github/utils/make_tests
.github/workflows/cpymad.yml
.github/workflows/make.yml
.github/workflows/manylinux.yml

Hi,
this PR fixes some bugs of the GitHub Actions configs.
The remaining errors seem to be actual test failures.
Resolves #987
Resolves hibtc/cpymad#79
Best, Thomas

Fix actions

---

src/mad_aper.c

The third parameter can be zero without any issues.

Fix racetrack aperture check. 

---

src/mad_twiss.c

Revert to the situation before but a more careful look should be done for all different situations. @rdemaria

Reverting the change in output of kicks.

---

Makefile_f90
libs/ptc/Makefile_f90

Ci_tpsa depends on Su_duan_zhe_map; add the required dependency

Add required dependency for Ci_tpsa

---

tests/test-twiss-10/test-twiss-10.madx
tests/test-twiss-10/test-twiss-10.ref

back compatiblity when updating the TWISS table.

Added a test of read/write of a pre-defined table. To check

---

doc/latexuguide/tables.tex

A small fix to the manual. Reported by Michi.

Small typo in the manual

---

src/mad_ibs.c

Single commit to fix my previous PR where I let through an unused variable :)

Remove unused variable
