MethodicalAcceleratorDesign/MAD-X

src/mad_const.c
src/mad_const.h
src/mad_extrn_f.h
src/mad_node.h
src/mad_twiss.c
src/mad_twiss.h
src/match.f90
src/matchjc.f90

The main change is to evaluate constraint values during twiss phase -> this allows to remove `match_data` from the `node` struct.
This change is also prerequisite for a later PR that will implement matching at intermediate positions (without creating nodes for all intermediate positions).

Improvements for the matching system

---

src/emit.f90
src/twiss.f90
src/util.f90

- handle centre option in `twcpgo`/`twchgo` instead of on each element
- a lot of cleanup on the structure of `twcpgo`/`twchgo`
- fix output of sigmat when centre is active
- fix a few inconsistencies with how centre was used (or not!) inside the elements
- tmcrab before the patch handled the center option in an extremely inconsistent manner, effectively calling twcptk multiple times via tmdrf

Refactor twiss

---

src/mad_const.c
src/mad_const.h
src/mad_dict.c
src/mad_match.c
src/mad_twiss.c
src/mad_twiss.h
src/twiss.f90

Currently works only when not using slow option. Fusing `twchgo` and `twcpgo` will be a precondition to make it work for slow option as well.
Note that this uses an additional argument `iindex` on the constraint to select for which interpolated slice the constraint should apply. I did not yet document this in case a cleaner solution is desired or if we should wait for it to work with slow.
I can adjust/patch as needed.

Implement matching at intermediate positions

---

src/twiss.f90

Required to make sectormap output compatible with interpolate/centre.
Since I never removed code where it was saved, I guess this was defect
for the old centre option.

Save values of sectormap

---

.gitignore
.travis.yml
Makefile
Makefile_lib
make/compiler.g++
make/compiler.gcc

This adds coverage reports for the C part automatically generated by Travis. I think it can be very useful to get a quick impression which parts of the code the tests don't even touch.
You also have to enable MAD-X on https://coveralls.io/repos/new

Coverage ci

---

src/mad_array.c
src/mad_cmd.c
src/mad_cmdin.c
src/mad_cmdpar.c
src/mad_expr.c
src/mad_name.c
src/mad_node.c
src/mad_stream.c
src/mad_table.c

In many places the `grow_XXX_array` functions are used to allocate an
additional array element directly before writing into the supposedly
allocated array index without further range-checks.
Now, if an array was initialized to zero length it was never grown,
meaning that we would write after the end of the allocated buffer.
This just caught me with the `select->at` parameter which has to have
zero length by default (as defined in mad_dict.c). If you specify one or
two values for `at`, everything *seemed* to work as expected. However,
`decode_par` did not properly grow the double array and was writing the
values after the end of the buffer. When specifying a third argument,
the problem manifested by writing a NUL into the first byte of the
`flag` buffer and hence not anymore executing any …

Fix growth of zero-length arrays

---

src/mad_seq.c

sequence.n_nodes was incorrect for all sequences with implicit drifts.

Fix double counting implicit drifts into n_nodes

---

src/util.f90

This should solve the problem with high-lumi masks.

Changed the maxiter for calculating eigenvalues. 

---

src/twiss.f90
src/util.f90

This is not a constraint for the formalism used in MAD-X and the check
is was simply wrong. The gammacp is actually never used except for check
the flimode.

Removed the check if gammacp > 1

---

src/mad_inter.c
src/mad_node.c
src/mad_node.h
src/mad_table.c

Hi,
this contains the fix for the bug introduced by #429 that Laurent described by mail to me: plotting the aperture table results results in a plot that stops at the first interpolated element. The reason is that the plotting routine works with `advance_to_pos` which uses `table::p_nodes` which were pointing to the temporary (invalid) nodes. With the fix, the table entry will always point to the template node that was used to interpolate the current node.
However, note that with this patch, while generating the expected plot, the example produces new warnings:
```
++++++ warning: double_from_table_row: column not found: aperture->k1l
++++++ warning: double_from_table_row: column not found: aperture->k1sl
++++++ warning: double_from_table_row: column not found: aperture->k2l
++++++ …
```

Fix aperture plot

---

src/mad_select.c
src/mad_select.h
src/mad_seq.c
src/mad_var.c

Resolves #492. 
The bug is due to an error on my part, introduced by 674555f5966d47e53cd3abccf08bf6b08f94b2c0. Back then, I didn't properly check that `pass_select` is used in two separate contexts:
- select elements by class + pattern
- select (var/seq) names by pattern only
Not properly handling the second case is the cause for #492.
The first commit restores the original behaviour (pre 674555f5966d47e53cd3abccf08bf6b08f94b2c0). The others fix flaws with the original handling of the second case:
`pass_select` should not consider SELECT statements in which CLASS appears as wildcards for variable/sequence names, because these were obviously meant to select elements.
Best, Thomas

Bugfix select

---

syntax/README.txt
syntax/atom/language-madx/CHANGELOG.md
syntax/atom/language-madx/LICENSE.md
syntax/atom/language-madx/README.md
syntax/atom/language-madx/grammars/madx.cson
syntax/atom/language-madx/package.json

This is just a first attempt at adding syntax highlighting for MadX in atom. It seems to work fine on all files I've tested it on, but there may be a few issues with erroneously highlighting parts variables with dots as numbers still.

MadX syntax highlighting version 0.1.2 for atom (experimental)

---

src/mad_select.c

Fixes #501.
Thanks @listoel for the minimal example.

Fix fetch_node_select crash when used with multiple sequences

---

src/mad_6track.c

This also makes it consistent with the nomrmal multipoles.

RF-multipole kick with phase 0 will be the same between Sixtrack and MAD-X.

---

src/mad_6track.c

When element names are 18 characters or longer, there are no more spaces separating one element from the next. This happens frequently when the aperture flag is added to sixtrack output. This fix adds a space at the end of the formatting to ensure it is always possible to split the elements on a single line.
This is a temporary fix. SixTrack does not support names longer than 16 characters. But this allows the files to be post processed before using them with SixTrack.

Fixed column separation in sixtrack export to fc.2

---

src/mad_table.c

Minor change so I can call out_table in cpymad without an actual output file.

Minor change for out_table

---

src/mad_const.c

Regression bug due to 345bd8632ecb1a7b6cd307b72af8fcb8d954007d.
Fixes #543.

Fix broken MVAR in "slow" matching

---

src/mad_cmdpar.c

Fixes parsing expressions such as:
beam, sequence=s1, -radiate;
which was so far parsed as:
beam, sequence="s1,-", radiate;
Example:
s1: sequence, l=1;
endsequence;
beam, sequence=s1, -radiate;
use, sequence=s1;
+=+=+= fatal: USE - sequence without beam: sequ

Fix parsing negated logical after string parameter

---

src/mad_twiss.c

Useful if you only need the table in memory. (In particular if using madx in cpymad)

Can set `sectorfile=""` to disable file IO

---

src/twiss.f90

Set `el=dl` _after_ calculating the multipole terms KNL/L since we have to use the full length L there.

Fix incorrect field errors in tmbend with INTERPOLATE

---

libs/gc/gc-7.2f/dyn_load.c
libs/gc/gc-7.6.4/dyn_load.c

Without this fix, the GC was not registering some pages that contained global variables, include the main and mostly used buffer c_dum. Hence, MADX was crashing during initialisation where many global buffers are preallocated.

GC bug: fix list of page attributes to check for registering pages as roots

---

src/mad_aper.c
src/mad_seq.h
src/mad_twiss.c

This PR fixes the issue that aperture gave wrong results with twiss, center. It is now a forbidden setting and mad-x do not output any aperture if this is chosen. The special case where there are only thin aperture object is accepted since the problem is creating the extra nodes needed for the extra slices.

Prevents aperture moduel to run with wrong setting of twiss

---

src/mad_cmdpar.c
src/mad_core.c
src/mad_elem.c
src/mad_elemerr.c
src/mad_err.c
src/mad_err.h
src/mad_match2.c
src/mad_ptc.c
src/mad_ptcknobs.c

This fixes a crash that occurs when linking madx dynamically to other applications. In this case, on linux the `error` function from `mad_err.c` will be interposed by [error(3)](https://linux.die.net/man/3/error) from the C stdlib (or vice versa, depending on the link order) which leads to segfaults once it is called - because the two function signatures differ.
If you don't like the rename, it could alternatively be solved by setting `__attribute__ ((visibility ("hidden")))` for `error`, but I think the better solution is to avoid the symbol collision altogether, which will also prevent any confusion if `<error.h>` is ever needed in madx.

Rename mad_error to avoid name collision with error(3)

---

doc/latexuguide/control.tex
doc/latexuguide/tables.tex
src/mad_select.c
src/mad_select.h
src/mad_seq.c
src/mad_var.c

Fix selecting by class=variable or class=sequence

---

src/trrun.f90

Track: fix bug in tilted thick quadrupole when k1s != 0 (tilt was added twice)

Bug fix in quad tilt in Track

---

doc/latexuguide/twiss.tex
src/mad_gcst.c

It also fixes the documentation for SECTORPURE.

This adds freqency to the SXFwrite 

---

src/mad_6track.c
src/mad_dict.c

We would like to have the ability to write more information in the `fc.2` file for import into SixTrack.
This PR adds a flag `multicol` to the SixTrack converter. This prints out the original element name, the single element name, and the element position in three columns. The first line of the block is `MULTICOL` so the SixTrack parser knows which format the block is in.

New flag in SixTrack converter for more info in file fc.2

---

src/touschek.f90

The problem was that there was a charge that was included in the calculations. This charge would have been correct if MAD-X would need a 180 deg change for positive and negative charged particles but since the acceleration is always in relation to the reference particle this doesn't make sense.
The old values were correct when there was a possessively charged particles but wrong in case of a negatively charged. This also fixes the issue #752

Touchek lifetime

---

CMakeLists.txt

I had accidentally added syntax that doesn't exist in cmake 2.8 and didn't realize until now.

Fix incompatibility with cmake 2.8

---

src/mad_elem.h
src/mad_extrn_f.h
src/mad_node.c
src/mad_node.h
src/mad_seq.c
src/mad_seq.h
src/mad_track.c
src/trrun.f90
src/util.f90

This PR reduces the time spend for tracking 4000 turns from 3m30sec to around 15 sec.

Tracking significant speed up

---

libs/gc/gc-8.0.2/gc_cpp.cc

Building clang 8 (and -std=c++1z) fails. The error message produced is:
```
/mnt/build/jenkins/workspace/lcg_release_latest/BUILDTYPE/Release/COMPILER/clang800binutils/LABEL/centos7/build/externals/madx-5.05.01/src/madx/5.05.01/libs/gc/gc-8.0.2/gc_cpp.cc:61:35: error: ISO C++17 does not allow dynamic exception specifications [-Wdynamic-exception-spec]
void* operator new(size_t size) GC_DECL_NEW_THROW {
^~~~~~~~~~~~~~~~~
/mnt/build/jenkins/workspace/lcg_release_latest/BUILDTYPE/Release/COMPILER/clang800binutils/LABEL/centos7/build/externals/madx-5.05.01/src/madx/5.05.01/libs/gc/gc-8.0.2/gc_cpp.cc:56:30: note: expanded from macro 'GC_DECL_NEW_THROW'
^~~~~~~~~~~~~~~~~~~~~
/mnt/build/jenkins/workspace/lcg_release_latest/BUILDTYPE/Release/COMPILER/clang800binutils/LABEL/centos7/build/externals/ …
```

No dynamic exceptions in ISO C++17

---

src/mad_eval.c
src/mad_parse.c
tests/test-line/test-line.madx
tests/test-line/test-line.ref

Fixes two parsing/evaluation bugs that occur when writing multiple statements on the same line involving a `LINE()` definition:
```
d: drift; myline: line=(d); beam;
use, sequence=myline;
-> +=+=+= fatal: USE - sequence without beam: myline
```
and:
```
kappa=0; myline: line=(drift);
beam;
use, sequence=myline;
-> ++++++ warning: unknown sequence skipped: myline
```
Note: these bug trigger whenever all statements are passed in the same `pro_input` call. This typically happens while reading from input files if they are on the same line, but also if they are within the same if/while construct, or if `pro_input` is called with text directly for some other reason, i.e:
```
if (1 == 1) {
d: drift;
myline: line=(d);
beam;
}
use, sequence=myline;
```
and:
```
if (1 == 1) {
kappa=0;
myline: …
```

Fix line parsing

---

src/mad_seq.c

This PR fixes the issue that if an element that is moved and other elements are reference to that element they will also be moved. 
This also has to be fixed for the keep_expression_move

Fixed the move command (old version)

---

doc/latexuguide/elements.tex
src/mad_mkthin.cpp
src/trrun.f90
src/twiss.f90

Fixes a number of reported issues

---

doc/latexuguide/match.tex
src/mad_match.c

Just prevents from segmentation fault when inputting weights made for "normal" matching when using: USE_MACRO

Fix seg fault weights

---

src/mad_dict.c
src/mad_expr.c
src/mad_mkthin.cpp
src/plot.f90
src/util.f90

First implementation of slicing with tapering by copying the new tap parameters in case of thick slicing and by adding them as expression to the corresponding multipole strength in case of thin slicing.
First implementation of wire collimator slicing : collimators with ilnorm will be translated to a simple collimator + a new thinwire at the centre of the collimator
Some minor changes outside makethin to increase c-chars to the maximum size allowed in plotting and to avoid >1 slices for rfcavity

slice tapering and wire collimator

---

src/trrun.f90
src/twiss.f90

Transformation of spatial coordinates in thin-cf approximation added. Furthermore, deltap-offset has been more clearly separated from the orbit(6) coordinate. Need checks.

Spatial coordinates in thin-cf

---

cmake/compilers/setupGNU.cmake

Modify the regex to catch the version number. 
Add the flag '-fallow-invalid-boz' to prevent compilation errors. 
Also make sure that other options are prepended correctly.

Add support for GFortran 10.x in Cmake.

---

.github/build_manylinux_cmake
.github/build_manylinux_make
.github/utils/ctest
.github/utils/is-static
.github/utils/make_tests
.github/utils/set-output
.github/workflows/cmake.yml
.github/workflows/cpymad.yml
.github/workflows/docs.yml
.github/workflows/make.yml
.github/workflows/manylinux.yml
CMakeLists.txt
cmake/compilers/setupGNU.cmake
tests/test-plot-2/test-plot-2.cfg

Hi,
this adds GitHub Actions configurations for building and testing MAD-X on several platforms. GitHub Actions is similar to Travis CI but more flexible. For reference, I listed some of its advantages at the very end.
Status so far:
- `make.yml`: build and test MAD-X on windows and linux using make
- `cmake.yml`: build and test MAD-X on linux using cmake; run configuration with several cmake versions to prevent introduction of incompatible syntax
- `manylinux.yml` build MAD-X in container conforming to manylinux standard, and test on several ubuntus
- `cpymad.yml` build and test cpymad master/release against current MAD-X commit
- `docs.yml` build documentation
- when tests fail, the corresponding `.out` files will be uploaded as build artifacts that can be downloaded after all jobs have …

Add GitHub Actions testing workflows

---

.github/workflows/make.yml

Hi,
thanks for merging my earlier PR:)
This is just a quick change I forgot to make: enable the coveralls upload when the secret is available. Also, removes the coveralls upload step on macos, which is currently built with `COVERAGE=no`.

Enable coverage upload on linux

---

src/mad_node.c

TRANSLATION is currently broken since node_value overrides a request for DX, DY, or DS by trying to pull them from the alignment structure. I add a check on whether current_node is a translation to prevent that.

Prevent node_value from overriding DX, DY, and DS for TRANSLATION

---

src/mad_6track.c

In some cases the fc.3 mult block cuts the highest order multipoles.

fix writing fc.3 mult block

---

src/madx_ptc_twiss.f90

A GCC 11 compile fails since tidy is called from within a loop indexed by i, and then the do loop in tidy modifies that same i through host association. I declared a local i in tidy to fix it.

Declare a local variable for the do loop index in subroutine tidy

---

src/mad_elem.c
src/mad_node.c
src/mad_table.c

This PR serves 2 purposes:
1. Restore node name internally table survey. This means internally it is now IP:1 instead of ip1
2. When an element is replaced, the keyword was not updated because the node was never updated. This is now fixed.

Name of element in survey table + wrong keyword when re-define an element

---

src/twiss.f90

It also fixes it for the elseparator and sextupoles.

This fixes the tilt in combination with centre option for quadrupole

---

src/mad_macro.c
src/twiss.f90

Found two buffer overflows:
1. make_macro does a strcpy, but doesn't allocate enough space for the null byte at the end
2. Fortran character arguments to get_value always need an extra space at the end, otherwise the ultimately called mycpy will overrun.

Fixed buffer overflow issues.

---

src/mad_ptc.c
src/mad_regex.c
src/mad_twiss.c

Fix gcc 11.2.0 warnings on MacOS

fix gcc warnings

---

src/emit.f90

Fix in the solenoid code in EMIT. The was a missing factor of two, due to the difference between the Wolski definition of solenoid strength and the MAD-X's one.

Fix in EMIT's solenoid

---

src/twiss.f90

`tmrefo` is not called from `twiss`, so there is no `twiss` to get the parameter from. This leads to a buffer overrun. I hardcoded a value for lack of a better solution. For the applications `tmrefo` is called for (`track`, `dynap`), it probably doesn't even matter if the orbit is stable, as long as the eigenvalues are not near +1.

In tmrefo, replace get_value from twiss with hardcoded eig_tol value.

---

src/trrun.f90

Tracking with thin lattice results in grossly wrong radiation damping in the longitudinal plan. A missing delta dependence found in the equations solve the issue
.

fix rad damping multipole

---

doc/latexuguide/beams.tex
doc/latexuguide/error.tex
doc/latexuguide/twiss.tex

Additional information about the difference between TWISS and ERROR tables handling of the BV flag and using LHC Beam 2 and Beam 4 as concrete examples.

Userguide: Additional info about bv flag

---

libs/ptc/src/Sa_extend_poly.f90
libs/ptc/src/Se_status.f90
libs/ptc/src/Sh_def_kind.f90
libs/ptc/src/cc_dabnew.f90
src/madx_ptc_module.f90

The particle type detection based on relative error is extended to 1e-4.
Clean TPSA I/O (PR restored), backward compatible (default madxprint=false in a_scratch_size.f90, used only by TPSA low level I/O routines in [c]c_dabnew.f90).
mapdump add one more level to dump maps to all orders (was limited to 1st order before).

Clean tspa io and some fixes

---

src/mad_node.c

name is a Fortran string and is not null terminated.
stoupper searches for the null termination.
Replace stoupper call by running toupper over the length of the Fortran string.

Fix potential buffer overrun when node_name calls stoupper

---

tests/test-survey-3/survey_chicane_patch.tfs.cfg
tests/test-survey-3/survey_chicane_sbend.tfs.cfg
tests/test-survey-3/survey_chicane_thin.tfs.cfg
tests/test-survey-3/survey_chicane_thinpatch.tfs.cfg

Differences showed up when testing with -O0.
Relative tolerance should be eliminated since we're checking values near zero.

Increase tolerance in test-survey-3. Remove relative tolerance.

---

src/mad_dict.c

This matches the behavior of all other elements
Should only matter for nonzero DS
Note: this does _not_ fix #1110; the example would work, but a simple change to the example by adding `exact=0` to the `translation` would trigger that bug.

Give TRANSLATION a default for EXACT to take EXACT from PTC_CREATE_LAYOUT

---

src/madx_ptc_module.f90

zero_key(key) sets key%exact equal to the value of exact_model
In the previous code, zero_key was called before exact_model was set,
and so key%exact was set based on node_value("exact ") of the previous node.
So, move the code to set exact_model to before zero_key is called.
Fixes #1110

Ensure that exact_model is set before zero_key is called

---

doc/latexuguide/control.tex
src/mad_dict.c
src/mad_stream.c

A missing file caused a problem in the upload of an optics. This was not spotted since JMAD runs in interactive mode and calling a missing file only triggers a warning. This PR adds a flag to make this fatal also in interactive mode. The default behaviour is as in the past.

Flag to throw fatal error when missing file in interactive mode.

---

src/madx_ptc_twiss.f90

when mapdump is activated, a special case was breaking ptc_twiss.

fix problem with mapdump and ptc_twiss

---

libs/ptc/src/Sa_extend_poly.f90

change single tpsa front markers to avoid confusion with full damap

update mdump format

---

src/trrun.f90

`trupdate` gives random errors since argument to `pro_input` is not null-terminated. Added the null termination and rewrote a bit.
I'm being a bit neurotic here, using `iso_c_binding` to call C from Fortran properly.
Really the interfaces should be put in an include file or module, but this is the only occurrence of this usage at the moment.
Ideally the code base switches from what is being done in `mad_extern_f.h` and `mad_types_f.h` to using `iso_c_binding`, but that's a larger undertaking.

Fix calls to pro_input from trupdate, adding null termination

---

.github/utils/set-output

See:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings

Replace deprecated ::set-output (will stop working in June 2023)

---

.github/workflows/cmake.yml
.github/workflows/cpymad.yml
.github/workflows/make.yml
.github/workflows/manylinux.yml
libs/ptc/src/Sh_def_kind.f90
tests/test-ptc-normal-5D-beambeam/leir.ptc.nonlin.cfg
tests/test-ptc-twiss-old5/test-ptc-twiss-old5.cfg

Fixes
- Remove _all_ uses of outdated ubuntu-18.04, which reached end of life on May 31, 2023
- Update the following actions due to Node 12 to Node 16 change
- Setup python v2 -> v4
-  download-artifact v2 -> v3
-  Update `old_thick_bend` to `true` 
- Revert leir.ptc.nonlin.cfg changes forcing test to not run (overall, just reduce the tolerances)
- Add more beta min max tolerances
After all of these fixes, all of the actions will pass, without warnings. Also, the actions will take somewhere around 20 minutes, instead of a day, since the actions do not hang waiting for an Ubuntu-18.04 machine.

Github Action Fixes

---

.github/workflows/docs.yml

Build will fail because of 404 error, so we need to update the repository data before doing the install

Action Fix 

---

Changes.md
doc/latexuguide/ibs.tex
src/ibsdb.f90
src/mad_ibs.c

Hello,
Since I have looked at the IBS module source code (ibsdb.f90) quite a lot for work recently, I figured it would be beneficial to submit a PR with an "improved" (as much as I could) documentation of this module.
**Important point: No code change is made in this PR.**
All this PR brings is a lot of comments trying to explain:
- What do things correspond to (variables, mostly)
- What is being done
- Why it is being done (sometimes)
I'm not 100% sure I am correct on everything in here, but almost all my additions should be correct and, hopefully, helpful.

IBS Table Fix and Code Source Comments

---

Changes.md
src/mad_cmd.c
src/mad_var.c
tests/test-addexpression/test-addexpression.ref

This PR fixes the issue in #1211. The problem is when there is an error in the add2expression this only manifest later because it is not shown. This is changed so now it is evaluated exactly in the same way as any other expression that is input.

Evaluates the Fix add2expression directly.

---

src/mad_cmd.c

The buff size is now the same as for the input line to avoid any issues in case of super long expressions..

Increased the buffer to avoid memory issues LONG expressions
